events/urls.py
from django.urls import path

from . import views

app_name = "events"

urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
    path("month_form", views.month_form, name="month_form"),
    path("search_form", views.search_form, name="search_form"),

    path("tag/<str:tag_name>", views.tag, name="tag"),

    path("tag_days/<int:days>/<str:tag_name>", views.tag_days, name="tag_days"),
    path("search_words/<int:days>/<str:words>", views.search_words, name="search_words"),
    path("stars_between/<int:days>/<int:lower_bound>/<int:upper_bound>", views.stars_between, name="stars_between"),

    path("month/<int:year>/<int:month>", views.month, name="month"),
    path("<int:days_back>", views.index, name="index_days_back"),
]

gratitude/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),
]

events/models.py
import datetime
from django.db import models

# Create your models here.


class EventType(models.Model):
    event_type_text = models.CharField(max_length=80)

    def __str__(self):
        return self.event_type_text


class Tag(models.Model):
    tag_text = models.CharField(max_length=80)

    class Meta:
        ordering = ['tag_text']

    def __str__(self):
        return self.tag_text


class Event(models.Model):
    event_day = models.DateField(default=datetime.date.today)
    event_type = models.ForeignKey(EventType, on_delete=models.CASCADE)
    event_description = models.CharField(max_length=200)
    event_details = models.TextField(blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    star_rating = models.IntegerField(default=1)

    class Meta:
        ordering = ['-event_day', '-id']

    def __str__(self):
        star = "\u2b50"
        return f"{self.event_day.strftime('%b. %d')} {self.star_rating * star} {self.event_type} {self.event_description}"

events/forms.py
import datetime
from django import forms
from .models import EventType, Tag


class DateInput(forms.DateInput):
    input_type = 'date'


class EventForm(forms.Form):
    event_day = forms.DateField(widget=DateInput, initial=datetime.date.today)
    event_type = forms.ModelChoiceField(queryset=EventType.objects.all(), initial=0)
    event_description = forms.CharField(label="Description", widget=forms.Textarea(attrs={'rows': 3, 'cols': 45}))
    event_details = forms.CharField(label="Details", widget=forms.Textarea(attrs={'rows': 6, 'cols': 45}), required=False)
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), required=False, widget=forms.SelectMultiple(attrs={'size': 8}))
    new_tags_comma_separated = forms.CharField(required=False)
    stars = range(1, 6)
    star_rating = forms.ChoiceField(choices=list(zip(stars, ('\u2b50' * i for i in stars))))

events/views.py
from datetime import datetime, timedelta

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from .models import Event, EventType, Tag
from .forms import EventForm


def index(request, days_back=7):
    return render(request, "events/index.html", {
        "events": Event.objects.filter(event_day__gt=datetime.now() - timedelta(days=days_back)),
    })


def tag(request, tag_name):
    return render(request, "events/index.html", {
        "events": Event.objects.filter(event_day__gt=datetime.now() - timedelta(days=30),
                                       tags__tag_text=tag_name),
    })


def month(request, year, month):
    return render(request, "events/index.html", {
        "events": Event.objects.filter(event_day__year=year, event_day__month=month)
    })


def search_words(request, days, words):
    return render(request, "events/index.html", {
        "events": Event.objects.filter(event_day__gt=datetime.now() - timedelta(days=days),
                                       event_description__icontains=words)
    })


def tag_days(request, days, tag_name):
    return render(request, "events/index.html", {
        "events": Event.objects.filter(event_day__gt=datetime.now() - timedelta(days=days),
                                       tags__tag_text=tag_name),
    })


def stars_between(request, days, lower_bound, upper_bound):
    return render(request, "events/index.html", {
        "events": Event.objects.filter(event_day__gt=datetime.now() - timedelta(days=days),
                                       star_rating__gte=lower_bound,
                                       star_rating__lte=upper_bound)
    })


def add(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event_day = form.cleaned_data['event_day']
            event_type = form.cleaned_data['event_type']
            event_description = form.cleaned_data['event_description']
            event_details = form.cleaned_data['event_details']
            tags = form.cleaned_data['tags']
            new_tags_comma_separated = form.cleaned_data['new_tags_comma_separated']
            star_rating = form.cleaned_data['star_rating']

            new_event_tags = []

            # add existing tags
            for tag in tags:
                if tag:
                    new_event_tags.append(Tag.objects.get(tag_text=tag))

            for new_tag_name in new_tags_comma_separated.split(','):
                if new_tag_name:
                    tag_object, created = Tag.objects.get_or_create(tag_text=new_tag_name.strip())
                    new_event_tags.append(tag_object)

            new_event = Event.objects.create(
                event_day=event_day,
                event_type=EventType.objects.get(event_type_text=event_type),
                event_description=event_description,
                event_details=event_details,
                star_rating=int(star_rating),
            )
            new_event.tags.set(new_event_tags)
            new_event.save()

            return HttpResponseRedirect(reverse('events:index'))
    else:
        form = EventForm()

    return render(request, "events/add_form.html", {'form': form})


def month_form(request):
    return render(request, "events/month_form.html")


def search_form(request):
    return render(request, "events/search_form.html")

events/templates/events/add_form.html
{% extends "events/base.html" %}

{% block content %}
<body>
  <form action="{% url 'events:add' %}" method="post">
    {% csrf_token %}
    <ul class="add-form">
      {{ form.as_ul }}
    </ul>
    <br><br>
    <input type="submit">
  </form>
</body>
{% endblock %}

events/templates/events/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'events/css/style.css' %}">
        <title>HC gratitude</title>
    </head>
    <body>
      <a href="{% url 'events:index' %}" class="header-link">7d</a>
      &bullet;
      <a href="{% url 'events:index_days_back' 90 %}" class="header-link">90d</a>
      &bullet;
      <a href="{% url 'events:add' %}" class="header-link">new</a>
      &bullet;
      <a href="{% url 'events:month_form' %}" class="header-link">mon</a>
      &bullet;
      <a href="{% url 'events:search_form' %}" class="header-link">srch</a>
      <div>
        {% block content %}
        {% endblock %}
      </div>
      <br><br>
      <a href="{% url 'admin:index' %}" class="footer-link">Admin</a>
      <br><br><br>
    </body>
</html>

events/templates/events/index.html
{% extends "events/base.html" %}

{% block content %}
<ul class="event-list">
  {% for event in events %}
  <li class="event">
    <span class="event-day">{{ event.event_day|date:"D, j M." }}</span>
    {% with ''|center:event.star_rating as range %}
    {% for i in range %}
    &#x2b50;
    {% endfor %}
    {% endwith %}

    <ul class="tag-list">
      {% for tag in event.tags.all %}
      <li class="tags">
        {% autoescape on %}
        <a href="{% url 'events:tag' tag %}" class="tag-link">
          {% endautoescape %}
          {{ tag }}
        </a>
      </li>
      {% endfor %}
    </ul>
    <div class="event-details">
      <strong>{{ event.event_type }}</strong>
      {{ event.event_description }}
      <p class="event-details-paragraph">{{ event.event_details }}</p>
    </div>
  </li>
  {% endfor %}
</ul>
{% endblock %}

events/templates/events/month_form.html
{% extends "events/base.html" %}

{% block content %}
<br>
<select id="year">
  <option value="{% now 'Y' %}">This year</option>
  <option value="2022">2022</option>
  <option value="2023">2023</option>
  <option value="2024">2024</option>
  <option value="2025">2025</option>
  <option value="2026">2026</option>
</select>

<select id="month">
  <option value="1">January</option>
  <option value="2">February</option>
  <option value="3">March</option>
  <option value="4">April</option>
  <option value="5">May</option>
  <option value="6">June</option>
  <option value="7">July</option>
  <option value="8">August</option>
  <option value="9">September</option>
  <option value="10">October</option>
  <option value="11">November</option>
  <option value="12">December</option>
</select>
<br><br>
<button onclick="goToMonth()">Go</button>
<br><br>
<script>
function goToMonth() {
  window.location = `/month/${document.getElementById("year").value}/${document.getElementById("month").value}`;
}
</script>
{% endblock %}

events/templates/events/search_form.html
{% extends "events/base.html" %}

{% block content %}
<h3>Search</h3>

Days back:
<select id="daysBack">
  <option value="1">1</option>
  <option value="3">3</option>
  <option value="7" selected>7</option>
  <option value="15">15</option>
  <option value="30">30</option>
  <option value="90">90</option>
  <option value="180">180</option>
  <option value="365">365</option>
</select>
<br>
<span style="color: red;" id="warning">&nbsp;</span>

<h4>Words</h4>
<input id="words">
<br>
<br>
<button onclick="goToWords()">Go</button>

<hr>

<h4>Tag</h4>
<input id="tag">
<br>
<br>
<button onclick="goToTag()">Go</button>

<hr>

<h4>Stars</h4>
From
<select id="lower">
  <option value="1">&#x2b50;</option>
  <option value="2">&#x2b50;&#x2b50;</option>
  <option value="3">&#x2b50;&#x2b50;&#x2b50;</option>
  <option value="4">&#x2b50;&#x2b50;&#x2b50;&#x2b50;</option>
  <option value="5">&#x2b50;&#x2b50;&#x2b50;&#x2b50;&#x2b50;</option>
</select>
To
<select id="upper">
  <option value="1">&#x2b50;</option>
  <option value="2">&#x2b50;&#x2b50;</option>
  <option value="3">&#x2b50;&#x2b50;&#x2b50;</option>
  <option value="4">&#x2b50;&#x2b50;&#x2b50;&#x2b50;</option>
  <option value="5" selected>&#x2b50;&#x2b50;&#x2b50;&#x2b50;&#x2b50;</option>
</select>
<br><br>
<button onclick="goToStars()">Go</button>

<hr>

<br><br>
<script>
function warn(msg) {
  document.getElementById("warning").innerText = msg;
}

function goToWords() {
  const days = document.getElementById("daysBack").value;
  const words = encodeURI(document.getElementById("words").value.trim());
  if (words.length >= 3) {
    window.location = `/search_words/${days}/${words}`;
  } else {
    warn("Please enter 3 or more characters.");
  }
}

function goToTag() {
  const days = document.getElementById("daysBack").value;
  const tag = encodeURI(document.getElementById("tag").value.trim());
  if (tag.length >= 1) {
    window.location = `/tag_days/${days}/${tag}`;
  } else {
    warn("Please enter 1 or more characters.");
  }
}

function goToStars() {
  const days = document.getElementById("daysBack").value;
  const lower = document.getElementById("lower").value;
  const upper = document.getElementById("upper").value;
  window.location = `/stars_between/${days}/${lower}/${upper}`;
}
</script>
{% endblock %}